// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from janus-client.djinni

#import <Foundation/Foundation.h>

@interface JanusVideoConstraints : NSObject
- (nonnull instancetype)initWithWidth:(int32_t)width
                               height:(int32_t)height
                                  fps:(int32_t)fps
                               camera:(nonnull NSString *)camera;
+ (nonnull instancetype)videoConstraintsWithWidth:(int32_t)width
                                           height:(int32_t)height
                                              fps:(int32_t)fps
                                           camera:(nonnull NSString *)camera;

@property (nonatomic, readonly) int32_t width;

@property (nonatomic, readonly) int32_t height;

@property (nonatomic, readonly) int32_t fps;

@property (nonatomic, readonly, nonnull) NSString * camera;

@end
